### ISSUE TITLE
Looking into using this with my project can you update usage

### ISSUE THREAD

**Issue by alexandru-calinoiu** [cloud66-oss/github-actions#1]
Hi,

Can you please update usage to the new yaml syntax. I want to try this out.

Thank you,

**Comment by ksaykova** [comment]
Hey,

Thanks for your comment! We are currently working with GitHub to release an Action that could be used with Cloud 66. However, since at the moment, they are subject to change, it is not recommended to use them for high-value workflows and content during the beta period. I believe the officially announce the release date for Actions is the 13th of November (as mentioned [here](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/)), so that would be the earliest we would have a Cloud 66 Action available as well.

Best,
Kris

**Comment by alexandru-calinoiu** [comment]
Ok, I can help test them out for you if you want, some other services already have actions in place.

**Comment by alexandru-calinoiu** [comment]
Hi guys, is the 13'th of nov, will you update the docs now?

**Comment by ksaykova** [comment]
Hey there! Thanks for the reminder - we will look into the updates that are needed in order for an action to be released and will update you once that's ready.

**Comment by alexandru-calinoiu** [comment]
Any updates for me guys here?

**Comment by alexandru-calinoiu** [comment]
By the looks of it you only need to update the docs, are the changes more involved that this?

**Comment by ksaykova** [comment]
Hey there! We've made some changes to Cloud 66 toolbelt since GHA v1 was released, so that would require additional work before releasing the action. Apologies for the inconvenience caused - we will update you with the progress of that.

**Comment by leoplct** [comment]
I tried with this
```
jobs:
  Test: 
   .....
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy To Cloud66
        uses: cloud66-oss/github-actions@1.0.0
        with:
          CLOUD66_STACK: "my_stack_name"
          CLOUD66_TOKEN: ${{ secrets.CLOUD66_TOKEN }} # cx dump-token | base64
```

but I got this error:
Warning: Unexpected input(s) 'CLOUD66_STACK', 'CLOUD66_TOKEN', valid inputs are ['entryPoint', 'args']
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown.

It's not much clear how to use it
